# Generated by Django 5.0.7 on 2024-07-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='badges/default_badge.jpg', upload_to='badges/')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('github_id', models.IntegerField(unique=True)),
                ('avatar_url', models.URLField()),
                ('badges', models.ManyToManyField(blank=True, to='repo.badge')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('issue_id', models.BigIntegerField(blank=True, default=None, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('url', models.URLField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pr_id', models.BigIntegerField(blank=True, default=None, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('labels', models.JSONField(default=list)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('badges', models.ManyToManyField(blank=True, to='repo.badge')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.contributor')),
            ],
        ),
    ]
